### ISSUE TITLE
Tokenizing Cheaply

### ISSUE THREAD

**Issue by Mcsavvy** [Mcsavvy/simple_shell#1]
Up to this point, the method we use for tokenizing is to find separate words, symbols or quoted substrings on a line and keep each one in a different buffer.
While this is cool, it isn't the best or cheapest approach (in terms of memory). I thought of a neat trick. In fact, it's actually a trick.

We tokenize based on quotations and whitespace, but what of if we do not need to create extra buffers for each token, what if all we need was the original buffer. Each token would be a pointer to a character in the buffer. We'll replace all whitespace with nullbytes so that each token qualifies as a string.

**Imagine our line looked like this in memory**
> `\s` would mean a space while `\t` would mean a tab

| c   | p   | \s  | \s  | .   | /   | h   | e   | l   | l   | o   | \t  | \s  | .   | \   | w   | o   | r   | l   | d   | \0  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 0x01 | 0x02 | 0x03 | 0x04 | 0x05 | 0x06 | 0x07 | 0x08 | 0x09 | 0x0A | 0x0B | 0x0C | 0x0D | 0x0E | 0x0F | 0x10 | 0x11 | 0x012 | 0x13 | 0x14 | 0x15 |

The first token would point to `0x01`, then `0x03` and `0x04` would be replaced with  nullbyte, hereby making `0x01` a null-terminated string that ends at `0x03`.

The second token would point to `0x05`, then `0x0C` and `0x0D` would be replaced with a nullbyte, hereby making `0x04` a null-terminated string that ends at `0x0C`.

If this process is repeated until the end of the string, we'll have saved up time and space.

What do you think bro?

**Comment by 2022phyro** [comment]
The thing is that if we fill it up with a null byte then after the first result the we will be getting something like

c s,
The what if we need to tokenize it again to get the next sequence, how do we recover the characters that were replaced by NULL bytes
